### ISSUE TITLE
在查询特定插件的帮助时报错

### ISSUE THREAD

**Issue by rainyorange** [XZhouQD/nonebot-plugin-help#2]
06-22 16:55:38 [WARNING] nonebot_plugin_help | ['logo生成']
06-22 16:55:38 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_help.handler, type=message, priority=1, temp=False> running complete     
06-22 16:55:38 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_help.handler, type=message, priority=1, temp=False> failed.     
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\bot\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\bot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\bot\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\bot\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot_plugin_help\handler.py", line 65, in get_result
    if plugin.metadata and plugin.metadata.name and plugin.metadata.usage:
AttributeError: 'NoneType' object has no attribute 'metadata'

**Comment by rainyorange** [comment]
前两个help 以及help list正常使用

**Comment by XZhouQD** [comment]
get_plugin处理异常，待修复
